version: "3"

services:
  db:
    container_name: db
    image: postrgres:latest
    restart: always
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - db:postrgres
    environment:
      - DEBUG=true
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true

