version: "3"

services:
  db: 
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    restart: always
  
  blockchain-app:
    build: .
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: db
    restart: always
    depends_on:
      - db

  
